---
version: '2'
services:
  local_news:
    build:
      context: .
      dockerfile: Dockerfile
    image: tibell/localnews:latest
    hostname: localnews
    container_name: local_news
    ports:
      - "8080:8080"
    environment:
      #KAFKA_HOST: '172.31.0.2:9092'
      KAFKA_HOST: 'broker:9092'
      KAFKA_ENABLED: 'false'
      KAFKA_TOPIC: 'local-news'
      SLACK_CALLBACK_URL: "${SLACK_CALLBACK_URL}"
      DISCORD_CALLBACK_URL: "${DISCORD_CALLBACK_URL}"
      DISCORD_CALLBACK_TOKEN: "${DISCORD_CALLBACK_TOKEN}"
      MYSQL_HOST: 'db'
      #MYSQL_HOST: 'mysql-db-1'
      MYSQL_USER: 'rasse'
      MYSQL_PASSWORD: 'password'
    networks:
      - mysql-net
      - kafka-net

networks:
  mysql-net:
    external: true
  kafka-net:
    external: true

#    networks:
#     - kafka-cluster_default
#
#networks:
#  kafka-cluster_default:

