version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/app?allowPublicKeyRetrieval=true
      spring.datasource.username: rasse
      spring.datasource.password: mypassword
      slack.callback.url: ${SLACK_CALLBACK_URL}
      discord.callback.url: ${DISCORD_CALLBACK_URL}
      discord.callback.token: ${DISCORD_CALLBACK_TOKEN}
    networks:
      - local-sub-net
    depends_on:
      - db
#      - amq

  db:
    image: mysql:8.0.36
    restart: unless-stopped
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
      MYSQL_USER: rasse
      MYSQL_PASSWORD: mypassword
    networks:
      - local-sub-net
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_init:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql

#  amq:
#    image: apache/activemq-artemis:2.32.0
#    ports:
#      - "8161:8161"
#      - "61616:61616"
#    environment:
#      ACTIVEMQ_ADMIN_LOGIN: admin
#      ACTIVEMQ_ADMIN_PASSWORD: admin
#    volumes:
#      - ./activemq:/var/lib/artemis-instance
#    networks:
#      - local-sub-net
#    depends_on:
#      - db

volumes:
  mysql-data:

networks:
  local-sub-net:
    driver: bridge